title: 'UniQ Dogs'
tagline: 'Les op maat!'

theme: null
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - yarn.lock
  - .gitignore
  - _site/

sass:
  sass_dir: _sass
